spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000

alibaba:
  cloud:
    access-key: LTAI5tBB3kqZ4bvgLPVQx1SV
    secret-key: AuUa3CvhGu9h0ZRS3KUtjZ0qkvO5Bt
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket: gulimall-heling